name: triton
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - pytest
  - pytorch
  - torchaudio
  - torchvision
  - typer
  - ca-certificates
  - certifi
  - openssl
  - zlib
  - zstd
  - llvm>=17.0
  - mlir>=17.0
